# zyhy-private-split config
# After editing: sudo zyhy-private-split apply
#   add hostname:  sudo zyhy-private-split add foo.hq.cmcc
#   add suffix:    sudo zyhy-private-split add '*.hq.cmcc'
#   add CIDR:      sudo zyhy-private-split add 172.16.0.0/16

WIFI_DOMAIN="ZYHY-Private"
DOMAINS="oa.hq.cmcc mail.cmhi.chinamobile.com"
SUFFIXES="hq.cmcc cmhi.chinamobile.com"
CIDRS="172.21.0.0/16 172.16.0.0/16"
